//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zametek.Utility.Encryption.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zametek.Utility.Encryption.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BytesToGenerate cannot be less than 32 bytes.
        /// </summary>
        internal static string Message_BytesToGenerateCannotBeLessThan32Bytes {
            get {
                return ResourceManager.GetString("Message_BytesToGenerateCannotBeLessThan32Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization vector must be 128-bit.
        /// </summary>
        internal static string Message_InitializationVectorMustBe128Bit {
            get {
                return ResourceManager.GetString("Message_InitializationVectorMustBe128Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations cannot be less than 500,000.
        /// </summary>
        internal static string Message_IterationsCannotBeLessThan500000 {
            get {
                return ResourceManager.GetString("Message_IterationsCannotBeLessThan500000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key cannot be less than 256-bit.
        /// </summary>
        internal static string Message_KeyCannotBeLessThan256Bit {
            get {
                return ResourceManager.GetString("Message_KeyCannotBeLessThan256Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must be 256-bit.
        /// </summary>
        internal static string Message_KeyMustBe256Bit {
            get {
                return ResourceManager.GetString("Message_KeyMustBe256Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must be 256-bit.
        /// </summary>
        internal static string Message_KeyMustBe256Bit1 {
            get {
                return ResourceManager.GetString("Message_KeyMustBe256Bit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt cannot be less than 256-bit.
        /// </summary>
        internal static string Message_SaltCannotBeLessThan256Bit {
            get {
                return ResourceManager.GetString("Message_SaltCannotBeLessThan256Bit", resourceCulture);
            }
        }
    }
}
